{ inputs, ... }:
{
  imports = [ inputs.treefmt-nix.flakeModule ];

  perSystem.treefmt = {
    programs = {
      deadnix.enable = true;
      nixfmt.enable = true;
      # Both read ruff.toml at the repository root.
      ruff-check.enable = true;
      ruff-format.enable = true;
      shellcheck.enable = true;
      statix.enable = true;
      # Reads .stylua.toml at the repository root.
      stylua.enable = true;
    };

    settings = {
      # Generated by nixos-generate-config; keep them regenerable rather than lint-clean.
      global.excludes = [ "hosts/*/hardware-configuration.nix" ];

      formatter = {
        # direnv's stdlib, not a standalone shell script.
        shellcheck.excludes = [ ".envrc" ];

        # Noctalia plugin scripts are Luau, which StyLua parses alongside Lua.
        stylua.includes = [ "*.luau" ];

        # Not yet ruff-clean; remove once users/jesse/dolphin's scripts are formatted and fixed.
        ruff-check.excludes = [ "users/jesse/dolphin/*.py" ];
        ruff-format.excludes = [ "users/jesse/dolphin/*.py" ];

        # Lint before formatting so fixes are formatted in the same run.
        deadnix.priority = 1;
        statix.priority = 2;
        nixfmt.priority = 3;
        ruff-check.priority = 1;
        ruff-format.priority = 2;
      };
    };
  };
}
