# Replace a "# request" command line with a shell command generated by Claude Code.
#
# Accepting the line sends the request to the signed-in Claude Code CLI and leaves the command
# in the buffer for review. Codex answers instead when Claude reports a usage limit or
# authentication failure. ZSH_CLAUDE_COMMAND_MODEL selects the Claude model, and
# ZSH_CLAUDE_COMMAND_PROMPT_EXTEND is appended to the system prompt. The @claude@-style
# placeholders are filled in by pkgs/zsh-claude-command/package.nix.

typeset -g ZSH_CLAUDE_COMMAND_MODEL="${ZSH_CLAUDE_COMMAND_MODEL:-}"
typeset -g ZSH_CLAUDE_COMMAND_PROMPT_EXTEND="${ZSH_CLAUDE_COMMAND_PROMPT_EXTEND:-}"

_zsh_claude_command_trim() {
  emulate -L zsh
  setopt extended_glob

  REPLY="${1##[[:space:]]#}"
  REPLY="${REPLY%%[[:space:]]#}"
}

_zsh_claude_command_classify_error() {
  emulate -L zsh

  local output="${(L)1}"

  if [[ "$output" == *"rate limit"* || "$output" == *"usage limit"*
    || "$output" == *"quota"* || "$output" == *"too many requests"* || "$output" == *"429"* ]]; then
    REPLY="usage limit"
  elif [[ "$output" == *"not authenticated"* || "$output" == *"unauthenticated"*
    || "$output" == *"authentication"* || "$output" == *"login required"*
    || "$output" == *"please log in"* || "$output" == *"invalid api key"*
    || "$output" == *"invalid_api_key"* || "$output" == *"401"* || "$output" == *"403"* ]]; then
    REPLY="authentication"
  else
    REPLY=""
  fi
}

_zsh_claude_command_normalize_response() {
  emulate -L zsh

  local response="${1//$'\r'/}"
  local backtick=$'\x60'
  local fence="${backtick}${backtick}${backtick}"

  _zsh_claude_command_trim "$response"
  response="$REPLY"

  if [[ "$response" == "$fence"* ]]; then
    response="${response#*$'\n'}"
    if [[ "${response[-4,-1]}" == $'\n'"$fence" ]]; then
      response="${response[1,-5]}"
    fi
    _zsh_claude_command_trim "$response"
    response="$REPLY"
  elif [[ "${response[1]}" == "$backtick" && "${response[-1]}" == "$backtick" ]]; then
    response="${response[2,-2]}"
  fi

  REPLY="$response"
}

_zsh_claude_command_accept_line() {
  # This is the hot path for every normal command: one builtin pattern match, then an immediate
  # handoff to Zsh's builtin accept-line widget.
  if [[ "$BUFFER" != '# '* ]]; then
    zle .accept-line
    return
  fi

  # Pasted scripts arrive as multiline buffers. Submit them normally so their comments never
  # become AI requests.
  if [[ "$BUFFER" == *$'\n'* ]]; then
    zle .accept-line
    return
  fi

  # Options are reset only for requests, keeping the hot path above free of setup.
  emulate -L zsh
  setopt no_aliases pipe_fail

  local system_prompt temp_dir error_file response_file prompt_file
  local response error_text exit_status claude_error_kind codex_error_kind message
  local -a claude_args
  local query="${BUFFER[3,-1]}"
  local provider="Claude"

  _zsh_claude_command_trim "$query"
  query="$REPLY"

  if [[ -z "$query" ]]; then
    zle .accept-line
    return
  fi

  system_prompt="You generate shell commands for an interactive zsh session.
Return exactly one syntactically correct, single-line command and nothing else.
Do not use Markdown, code fences, comments, or explanations.
The command must be safe to review: never claim that it has already run.
Operating system: $OSTYPE. Current directory: $PWD.
Prefer rg over grep, fd over find, bat over cat, and eza over ls."

  if [[ -n "$ZSH_CLAUDE_COMMAND_PROMPT_EXTEND" ]]; then
    system_prompt+=$'\n'"$ZSH_CLAUDE_COMMAND_PROMPT_EXTEND"
  fi

  claude_args=(
    --print
    --output-format text
    --safe-mode
    --no-session-persistence
    --permission-prompts none
    --tools ''
    --effort low
    --system-prompt "$system_prompt"
  )
  if [[ -n "$ZSH_CLAUDE_COMMAND_MODEL" ]]; then
    claude_args+=(--model "$ZSH_CLAUDE_COMMAND_MODEL")
  fi

  zle -M "Generating command with Claude…"
  zle redisplay

  temp_dir="$("@mktemp@" -d "${TMPDIR:-/tmp}/zsh-claude-command.XXXXXX")"
  if (($? != 0)) || [[ -z "$temp_dir" ]]; then
    zle -M "CLI error: could not create temporary files; your buffer was left unchanged"
    return 0
  fi

  error_file="$temp_dir/error"
  response_file="$temp_dir/response"
  prompt_file="$temp_dir/system-prompt"
  print -r -- "$system_prompt" >"$prompt_file"

  response="$("@claude@" "${claude_args[@]}" -- "$query" 2>"$error_file")"
  exit_status=$?

  if ((exit_status != 0)); then
    error_text="$(<"$error_file")"
    _zsh_claude_command_classify_error "$error_text"
    claude_error_kind="$REPLY"

    if [[ -z "$claude_error_kind" ]]; then
      "@rm@" -rf -- "$temp_dir"
      zle -M "CLI error: Claude failed (exit $exit_status); your buffer was left unchanged"
      return 0
    fi

    zle -M "Claude $claude_error_kind unavailable; trying Codex…"
    zle redisplay

    "@codex@" exec \
      --ephemeral \
      --ignore-user-config \
      --ignore-rules \
      --skip-git-repo-check \
      --sandbox read-only \
      --color never \
      --output-last-message "$response_file" \
      --config "model_instructions_file=\"$prompt_file\"" \
      -- "$query" \
      >/dev/null 2>"$error_file"
    exit_status=$?

    if ((exit_status != 0)); then
      error_text="$(<"$error_file")"
      _zsh_claude_command_classify_error "$error_text"
      codex_error_kind="$REPLY"
      "@rm@" -rf -- "$temp_dir"

      message="CLI error: Claude $claude_error_kind; "
      if [[ -n "$codex_error_kind" ]]; then
        message+="Codex $codex_error_kind. "
      else
        message+="Codex failed (exit $exit_status). "
      fi
      zle -M "${message}Your buffer was left unchanged"
      return 0
    fi

    response="$(<"$response_file")"
    provider="Codex"
  fi

  "@rm@" -rf -- "$temp_dir"
  _zsh_claude_command_normalize_response "$response"
  response="$REPLY"

  if [[ -z "$response" || "$response" == *$'\n'* ]]; then
    zle -M "$provider returned an empty or multiline response; your buffer was left unchanged"
    return 0
  fi

  BUFFER="$response"
  CURSOR="${#BUFFER}"
  zle -M ""
  zle redisplay
}

zle -N accept-line _zsh_claude_command_accept_line
